[package]
name    = "pacman"
version = "0.1.0"
authors = ["hawkings"]

[dependencies]
docopt       = {version = "*"}
termios      = {version = "*"}
serde        = {version = "*"}
serde_derive = {version = "*"}